server:
  port: 8099

spring:
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
    static-path-pattern: /static/**
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
